### ISSUE TITLE
Add logic to deal with overlapping ajax requests

### ISSUE THREAD

**Issue by johndigital** [funkhaus/vuehaus#121]
On any Vuepress site if you navigate several consecutive pages quickly you can usually break the site. This is (I think) because consecutive ajax requests are being made before the first one can finish. Then by the time it does finish it's the wrong data for the page the user is on.

We just need to add some logic to deal with this, cancelling older requests when newer ones are made.

**Comment by SaFrMo** [comment]
Fixed in 9a43740! Dispatching `LOAD_AND_REPLACE_QUERYDATA` sets the store's `currentlyFetching` to the desired path. The response is cached and, if that response's path matches `currentlyFetching`, the query data is replaced. This way we still get the benefit of caching requested info, but only the latest path's data is actually displayed on the site.
