### ISSUE TITLE
Make deploy use production build of Vue

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuehaus#133]
If I do `npm run deploy`, the console on the live site gives a warning saying Vue is in development mode. 

```
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

The server does not have `wp-debug` turned on in flywheel,

Flywheel local is not in `debug` mode when I ran `npm run deploy`.

**Comment by johndigital** [comment]
Well, that's the way it was intended but I can definitely see why it's confusing.

The deploy command is only meant to just push the files up the server and nothing else, so it assumes you've already run the build command. I like having them separate because there are times when you might want to test the production version on local and vice versa where you want the vue dev tools available on the server. Currently I just do `npm run build && npm run deploy` which does what you're expecting.

Given that explanation @drewbaker do you think it make sense to keep them separate or combine them together? It's a pretty easy change either way.

**Comment by drewbaker** [comment]
OK I didn't know it worked that way at all. Seems like we should make it a boolean parameter in the `.deployrc.json` file. Default would be to make production builds I think.

Because you can now set `production` and `staging` deploy paths, seems to me when you deploy to production, the default should be to make a production build.

**Comment by SaFrMo** [comment]
@drewbaker I might shy away from making it a parameter in `.deployrc`, just because that file is the config for the `fh-deploy` and is supposed to be more of a "give me a bunch of files to upload and I'll do it" instruction than a build step.

We could switch the `npm run deploy` command to do `npm run build && fh-deploy`, but like John mentioned I usually just do `npm run build && fh-deploy`, since it's usually a good idea to be explicit about the files being deployed to the server.

If you wanted, you could set an alias in your [bash profile](https://natelandau.com/my-mac-osx-bash_profile/) to simplify things:

```sh
alias deploy="npm run build && fh-deploy production"
```

Then you could just run `deploy` to build and deploy in one command. This builds the site in your current directory and tries to deploy to `production`. 

If there's no `production` environment in your `.deployrc` file, it'll fail with this: 

![error message reading "Can't find target environment production! No action taken."](https://user-images.githubusercontent.com/5344587/49524398-ad7a3a00-f879-11e8-939d-fd794a651f59.png)

If that's the case, delete `.deployrc.json`, run `fh-deploy` to rebuild it, and run `deploy` again.

**Comment by drewbaker** [comment]
It seems backwards to me, but if you guys want to keep it this way, then can you update the Vuehaus deploy instructions to reflect that a deploy will just upload whatever is in your directory at the time. Current the docs say it does an npm run build first.

**Comment by SaFrMo** [comment]
Will do!

**Comment by SaFrMo** [comment]
Added in 8674d3a!
