### ISSUE TITLE
Asynchronous Issues potentially?

### ISSUE THREAD

**Issue by mrkylemac** [funkhaus/vuehaus#135]
I was hoping I could pester you guys quickly about something I've been seeing happen when I'm building with Vuehaus, ```(old data showing before new data is ready on new routes)``` would love wider knowledge on why it could be happening...

For example, this site is made up of posts, all within categories that make up the nav: featured, stop motion etc. 

With every click (before cache), I can see the old data before the new data appears?
Here's a screencast: https://jmp.sh/AzniLWm

Thanks!

**Comment by SaFrMo** [comment]
Hey! That's because the new data hasn't finished fetching yet and the new template likely isn't checking the loading state before rendering.

A lot of times I'll add a `v-if="$store.state.loaded` to the main wrapper of a component - for example:

```html
<template>
  <main class="post-grid" v-if="$store.state.loaded">
    <!-- content here -->
  </main>
</template>
```

That way the `main` element won't actually render until the data has finished loading. This also means that if you wrap the `main` element in a `transition`, that `transition` won't run until the data is loaded, which can be pretty handy. 

Hopefully that answers your question - let us know if it doesn't!

**Comment by mrkylemac** [comment]
Thanks/Hi Sander! 

I wasn't far from your approach above, except I wasn't including ```transition``` beneath the v-if, which now looks smooth. Appreciate the help!
